### PR TITLE
Add new tweet: announce “Improve your documentation with Mermaid.js diagrams”

### PR DESCRIPTION
**Pull request by sftim**
Announce the blog article [Improve your documentation with Mermaid.js diagrams](https://www.kubernetes.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/)

### CODE REVIEW

**Review by Debanitrkl — APPROVED** [review]
/lgtm

**Review by rajula96reddy — APPROVED** [review]
/lgtm /approve

**Comment by Debanitrkl** [comment]
The tweet didn't go out I guess @chris-short I think you have to manually tweet this

**Comment by sftim** [comment]
I scheduled it for 21:00 and it's not 21:00 yet, so maybe all is well?

**Pull request merged**
