### PR TITLE
Initial setup to automate tweets through github action workflows

### PR DESCRIPTION
**Pull request by rajula96reddy**

### CODE REVIEW

**Comment by chris-short** [comment]
Credentials passed to @mrbobbytables to enter it GitHub Actions secrets.

**Comment by mrbobbytables** [comment]
They were added a little bit ago, sorry for the delay^^;;;;

**Comment by kaslin** [comment]
As far as the code goes,
/lgtm
we'll have to come up with a plan for the readme later.

**Comment by chris-short** [comment]
Do they work is the question, @rajula96reddy

**Comment by rajula96reddy** [comment]
@chris-short We will only know if it is working, when the PR is merged.

**Comment by rajula96reddy** [comment]
@chris-short @kaslin Can we merge and check this?

**Comment by nikhita** [comment]
@mbbroberg needs `/approve` instead of `/approved` :D

**Comment by mbbroberg** [comment]
Shwoops @nikhita :D 

/approve

**Comment by nikhita** [comment]
> @kaslin: changing LGTM is restricted to collaborators

@kaslin btw you should also be able to lgtm/approve PRs once you accept the invite at https://github.com/kubernetes-sigs :)

**Comment by mbbroberg** [comment]
@nikhita anything I can do to trigger it to recheck other than be patient? :smile:

**Comment by nikhita** [comment]
Just trying something, this shouldn't be able to approve...

/approve

**Comment by nikhita** [comment]
prow, you are growing old :)

**Pull request merged**
