### PR TITLE
Fix: Automated Tweet via Issue

### PR DESCRIPTION
**Pull request by gkarthiks**
This PR is aimed to fix the anomalies observed from issue #40.

### Note:
We need to have a label as `tweet`, because that's what the action will look for in the issue and only run the remaining process if that satisfies.

This can be any label, but the label name needs to go in the workflow main.yml against the key `tweet-label-id`.

In this same PR, I also moved the issue templates in the right structure. So, now there will be an issue template to get started with.

The there thing to note is, we are still with the `master` naming convention for the default branch. I guess we can change that to `main`. When that's done, we gotta change the `base` from master to main under the `pull-request` action in the same workflow main.yml file.

/cc @rajula96reddy @kaslin @mrbobbytables @mbbroberg

### CODE REVIEW

**Comment by rajula96reddy** [comment]
Hey @gkarthiks Quick question. With the new changes, can we publish a tweet from a PR (without issue -> PR)?
Because we weren't able to do this in one of the latest PRs https://github.com/kubernetes-sigs/contributor-tweets/pull/44

**Comment by gkarthiks** [comment]
@rajula96reddy  the answer is yes. Because the pull request action is out of this issue action.

**Comment by rajula96reddy** [comment]
@gkarthiks Great. Thanks. This PR lgtm. Do we have any more changes to make?

**Comment by gkarthiks** [comment]
@rajula96reddy no Rajula. This should be the final one for this first feature.

**Pull request merged**
