### PR TITLE
Create 07-05-2021-first-tweet.tweet

### PR DESCRIPTION
**Pull request by rainleander**

### CODE REVIEW

**Comment by rainleander** [comment]
This tweet may not be relevant anymore... Can I help moderate these pulls?

**Review by mbbroberg — COMMENTED** [review]
LOVE this! Wdyt @kaslin?

**Comment by mbbroberg** [comment]
Hey @rainleander, we'd love to get your involvement here. @kaslin is lead and we could talk you coming in as shadow or another contributor in general.

**Comment by rainleander** [comment]
> Hey @rainleander, we'd love to get your involvement here. @kaslin is lead and we could talk you coming in as shadow or another contributor in general.

Definitely; I'm comfortable doing either!

**Comment by kaslin** [comment]
Ah yeah, I'm so sorry I missed this back when you submitted it! KubeCon threw me off. But yes, I love it! I'm tempted to just go ahead and send it anyway. I can add a reply on it with more context.

**Comment by rainleander** [comment]
Yeah, it's a tornado. Definitely reply to add context once it goes through. I can do the same!

**Comment by kaslin** [comment]
Sorry about the additional delay on this, we're definitely learning some about our processes here! We just introduced some new automation to the repo which broke things for a minute, so this tweet will serve an additional purpose as a test in the process of our automation updates!

Thank you, @rainleander for unintentionally becoming the first member of our automation testing team! XD (This is a joke about the testing team, but really thank you! This PR makes me so happy.)

**Comment by rainleander** [comment]
No worries at all; let's get it all going smoothly!

**Comment by rajula96reddy** [comment]
Hey! The workflow should be fixed. Commenting here, for it to trigger properly.

**Comment by rajula96reddy** [comment]
Hey @rainleander Thanks for being patient. The workflow should be fixed now. Do you rebasing this PR on the latest master branch? Thanks!

**Comment by rainleander** [comment]
> Hey @rainleander Thanks for being patient. The workflow should be fixed now. Do you rebasing this PR on the latest master branch? Thanks!

Done!

**Comment by rajula96reddy** [comment]
> > Hey @rainleander Thanks for being patient. The workflow should be fixed now. Do you rebasing this PR on the latest master branch? Thanks!
> 
> Done!

Correct me if I am wrong, I don't see the rebase changes. Can you check again?
https://github.com/rainleander/contributor-tweets/tree/patch-1 still says "This branch is 1 commit ahead, 13 commits behind kubernetes-sigs:master. "

**Comment by rainleander** [comment]
Weird. Did it again?

**Comment by rajula96reddy** [comment]
> Weird. Did it again?

I can the new changes now. The workflow is working. The tweet will go out once we merge this.

Just an FYI for future purposes: It is advised to not do a merge rebase if possible, it creates an additional commit. A normal rebase is preferred.

**Pull request merged**
