### PR TITLE
Tweet for lifecycle survey

### PR DESCRIPTION
**Pull request by mbbroberg**
Signed-off-by: Matthew Broberg <matt@opensource.com>

### CODE REVIEW

**Comment by mbbroberg** [comment]
Hey @parispittman or @kaslin or @rajula96reddy -- could you give me a /lgtm when you get a chance?

**Comment by rajula96reddy** [comment]
Hey @mbbroberg I see similar tweets sent out twice today
https://twitter.com/K8sContributors/status/1295631522104573954?s=20
https://twitter.com/K8sContributors/status/1295497714377961473?s=20

Should we do another one?

**Comment by mbbroberg** [comment]
Oh cool - I think one more wouldn't be a problem :smile:

**Pull request merged**
