### PR TITLE
Create 09-18-2020-wg-naming-intro.tweet

### LINKED ISSUE #16: [Request for New Tweet] WG Naming tweet request
## Tweet content:
```
Looking for a way to make K8s better? Join WG Naming and contribute to naming conventions, and inclusive language! (https://bit.ly/35TWwIO)
```

## Tweet time:
Please wait for the approval from @celestehorgan @jdumars @justaugustus @zacharysarah

## Urgency: Medium

/cc @kaslin

### PR DESCRIPTION
**Pull request by gkarthiks**
Fixes #16 

/cc @kaslin

### CODE REVIEW

**Review by justaugustus — CHANGES_REQUESTED** [review]
From https://github.com/kubernetes-sigs/contributor-tweets/issues/16#issuecomment-695015918:

> Looking for a way to make #Kubernetes better? Join WG Naming and contribute to the discussion on inclusive language and naming conventions! (https://bit.ly/35TWwIO)

Let's do this ^^
- spell out Kubernetes and use the hashtag
- drop the Oxford comma

**Comment by celestehorgan** [comment]
/approve

Leave the hold on until the 1st week of October please1

**Comment by gkarthiks** [comment]
Reminder for @celestehorgan to unhold this in this week.

**Pull request merged**
